AUDIT UPDATE,INSERT,DELETE ON USUARIO BY ACCESS WHENEVER SUCCESSFUL;
AUDIT UPDATE,INSERT,DELETE ON EMPRESA BY ACCESS WHENEVER SUCCESSFUL;
AUDIT UPDATE,INSERT,DELETE ON DENUNCIA BY ACCESS WHENEVER SUCCESSFUL;