CREATE OR REPLACE VIEW V_ULTIMABUSQUEDA ("ALIAS","ULTIMABUSQUEDA")AS (SELECT U.ALIAS, MAX(H.TERMINO) FROM USUARIO U, HISTORIALV1 H
WHERE U.ID_USUARIO=H.USUARIO_ID_USUARIO
GROUP BY U.ALIAS);

CREATE OR REPLACE VIEW V_ULTIMOVIDEO AS
  (SELECT U.ALIAS, MAX(V.FECHA_CREACION) AS ULTIMOVIDEO FROM USUARIO U, VIDEO V
  WHERE U.CANAL_ID_CANAL = V.CANAL_ID_CANAL
GROUP BY ALIAS);

CREATE OR REPLACE VIEW ULTIMO_COMENTARIO AS
  (SELECT U.ALIAS, MAX (C.FECHA)AS ULTIMOCOMENTARIO FROM USUARIO U, COMENTARIO C
  WHERE C.USUARIO_ID_USUARIO = U.ID_USUARIO
GROUP BY ALIAS);

CREATE OR REPLACE PROCEDURE P_INACTIVO AS
  UC DATE;
  UV DATE;
  UH DATE;
  CONTADOR NUMBER;
  SENTENCIA VARCHAR2(500);
BEGIN 
  LOCK TABLE USUARIO IN SHARE MODE;
  LOCK TABLE COMENTARIO IN SHARE MODE;
  LOCK TABLE VIDEO IN SHARE MODE;
  LOCK TABLE HISTORIALV1 IN SHARE MODE;
  DECLARE CURSOR U_ALIAS IS SELECT ID_USUARIO, ALIAS FROM USUARIO;
  BEGIN
    FOR VAR_CURSOR IN U_ALIAS LOOP
      CONTADOR:=0;
      SELECT ULTIMOCOMENTARIO INTO UC FROM ULTIMO_COMENTARIO WHERE ALIAS=VAR_CURSOR.ALIAS;
      SELECT ULTIMABUSQUEDA INTO UH FROM V_ULTIMABUSQUEDA WHERE ALIAS=VAR_CURSOR.ALIAS;
      SELECT ULTIMOVIDEO INTO UV FROM V_ULTIMOVIDEO WHERE ALIAS=VAR_CURSOR.ALIAS;
      IF UC IS NULL OR SYSDATE-UC>30 THEN
        CONTADOR:=CONTADOR+1;
      END IF;
      IF UH IS NULL OR SYSDATE-UH>30 THEN
        CONTADOR:=CONTADOR+1;
      END IF;
      IF UV IS NULL OR SYSDATE-UV>30 THEN
        CONTADOR:=CONTADOR+1;
      END IF;
      IF CONTADOR=3 THEN
        GESTION_USUARIOS.BORRADO(VAR_CURSOR.ID_USUARIO);
      END IF;
    END LOOP;
  END;
  COMMIT;
END;
/
/*
/
--en system dar privilegios:
--grant create job to u_administrador;
begin
DBMS_SCHEDULER.CREATE_JOB (
    job_name=> 'borrado_semanal',
    job_type=> 'STORED_PROCEDURE',
    job_action => 'P_INACTIVO',
    start_date => sysdate,
    repeat_interval => 'FREQ=WEEKLY;BYDAY=FRI'
    );
end;
/
exec dbms_scheduler.enable('borrado_semanal');
*/
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
            job_name => '"ADMINISTRADOR_U"."BORRADO_SEMANAL"',
            job_type => 'STORED_PROCEDURE',
            job_action => 'ADMINISTRADOR_U.P_INACTIVO',
            number_of_arguments => 0,
            start_date => SYSDATE,
            repeat_interval =>'FREQ=WEEKLY;BYDAY=FRI',
            end_date => NULL,
            enabled => FALSE,
            auto_drop => FALSE,
            comments => '');

         
     
 
    DBMS_SCHEDULER.SET_ATTRIBUTE( 
             name => '"ADMINISTRADOR_U"."BORRADO_SEMANAL"', 
             attribute => 'logging_level', value => DBMS_SCHEDULER.LOGGING_OFF);
      
  
    
    DBMS_SCHEDULER.enable(
             name => '"ADMINISTRADOR_U"."BORRADO_SEMANAL"');
END;
-->>>>>>> master

exec dbms_scheduler.enable('BORRADO_SEMANAL');
