CREATE OR REPLACE PROCEDURE DESBLOQUEAR_USUARIO 
(
  ALIAS IN VARCHAR2 
) AS
  SENTENCIA VARCHAR2(500);
BEGIN
  SENTENCIA:= 'ALTER USER '|| ALIAS ||' ACCOUNT UNLOCK' ;
  EXECUTE IMMEDIATE SENTENCIA;
END DESBLOQUEAR_USUARIO;