create or replace PROCEDURE DESCONECTAR AS 
SENTENCIA varchar2(200);
BEGIN
 DECLARE 
        CURSOR BLOQUEAR_CURSOR IS SELECT NOMBRE FROM USUARIO WHERE BORRADO='S';
      BEGIN
        FOR VAR_CURSOR IN BLOQUEAR_CURSOR LOOP
        SENTENCIA:= 'REVOKE CONNECT FROM ' || VAR_CURSOR.NOMBRE;
        EXECUTE IMMEDIATE SENTENCIA;
      END LOOP;
      END;
END DESCONECTAR;