alter table video_pago
add constraint CK_COSTE
check (COSTE >= 1);

ALTER TABLE VIDEO
ADD CONSTRAINT CK_POSITIVOS
CHECK (N_VISUALIZACIONES >= 0 AND N_COMENTARIOS >=0 AND N_MEGUSTA >=0
AND N_MEGUSTA >=0 AND N_NOMEGUSTA >=0);

