CREATE OR REPLACE TRIGGER CONTROL_SUBSCRIPCIONES
AFTER INSERT OR DELETE ON SUBSCRIPCIONES
FOR EACH ROW
DECLARE
SUBS NUMBER;
BEGIN
  SELECT SUBSCRIPTORES INTO SUBS FROM CANAL WHERE ID_CANAL = :NEW.CANAL_ID_CANAL;
  IF INSERTING THEN
     UPDATE CANAL SET SUBSCRIPTORES = SUBS +1
       WHERE ID_CANAL = :NEW.CANAL_ID_CANAL;
    
  ELSIF DELETING THEN
    UPDATE CANAL SET SUBSCRIPTORES = SUBS - 1
       WHERE ID_CANAL = :OLD.CANAL_ID_CANAL;
  END IF;
END CONTROL_SUBSCRIPCIONES ;
/