create tablespace MITUBO_ESPACE datafile 'C:\app\alumnos\mitubo_espace.dbf' size 1G autoextend on; 
create tablespace ESPACE_GENTE datafile 'C:\app\alumnos\espace_gente.dbf' size 500M autoextend on; 

CREATE PROFILE MITUBO_PERF LIMIT FAILED_LOGIN_ATTEMPTS 3 IDLE_TIME 5;

CREATE ROLE CONSULTOR;
GRANT CONNECT TO CONSULTOR; 
GRANT SELECT ON viewhacer TO CONSULTOR;
CREATE USER CONSULTOR IDENTIFIED BY bd PROFILE MITUBO_PERF
ON ESPACE_GENTE DEFAULT TABLESPACE ESPACE_GENTE;

CREATE ROLE AGENTE;
GRANT SELECT, DELETE  ON DENUNCIA TO AGENTE;
GRANT DELETE ON VIDEO TO AGENTE;
GRANT INSERT, DELETE ON NOTIFICACION TO AGENTE;
GRANT CONNECT TO AGENTE; 
CREATE USER AGENTE IDENTIFIED BY bd PROFILE MITUBO_PERF
ON ESPACE_GENTE DEFAULT TABLESPACE ESPACE_GENTE;

CREATE ROLE ADMINISTRADOR;
GRANT CONNECT TO ADMINISTRADOR; 
GRANT RESOURCE TO ADMINISTRADOR;
CREATE USER ADMINISTRADO IDENTIFIED BY bd PROFILE MITUBO_PERF QUOTA 1G 
ON MITUBO_ESPACE DEFAULT TABLESPACE MITUBO_ESPACE;
GRANT ADMINISTRADOR to ADMINISTRADO;

CREATE ROLE USUARIO;
GRANT CONNECT TO USUARIO; 
GRANT SELECT on viewhacer to usuario;
CREATE USER USUARIO IDENTIFIED BY bd PROFILE MITUBO_PERF
ON ESPACE_GENTE DEFAULT TABLESPACE ESPACE_GENTE;

