--Creamos las vistas tanto para administrador como para un usuario concreto
--Desde U_ADMINISTRADOR
CREATE  VIEW Pago_TOTAL_VIDEO AS (select (pago*video.N_VISUALIZACIONES) PAGO_TOTAL,
 video.ID_VIDEO, video.TITULO  from video , pago where video.ID_VIDEO=pago.VIDEO_ID_VIDEO
) with read only;

CREATE  VIEW CANAL_DINERO_TOTAL AS (select  canal.ID_CANAL, sum(pago.PAGO*video.N_VISUALIZACIONES) pago, canal.NOMBRE
 from video, canal, pago 
 where video.CANAL_ID_CANAL= canal.ID_CANAL and video.ID_VIDEO=pago.VIDEO_ID_VIDEO 
 group by canal.ID_CANAL, canal.NOMBRE
)with read only;

CREATE  VIEW VIDEOS_CON_DENUNCIA AS (select video.ID_VIDEO, DENUNCIA.ID_DENUNCIA 
from video, DENUNCIA, RELATION_13 
where RELATION_13.VIDEO_ID_VIDEO=video.id_video 
and RELATION_13.DENUNCIA_ID_DENUNCIA=DENUNCIA.ID_DENUNCIA
)with read only;

CREATE  VIEW VIDEO_ESTADISTICAS  AS (select ID_VIDEO, N_MEGUSTA, N_VISUALIZACIONES, 
N_NOMEGUSTA, N_COMENTARIOS from video
)with read only;

CREATE  VIEW PORCENTAJES_VIDEO AS (SELECT ID_VIDEO, (N_MEGUSTA/N_VISUALIZACIONES*100) porcentaje_likes,
(N_NOMEGUSTA/N_VISUALIZACIONES*100) porcentaje_no_likes  FROM video
)with read only;

CREATE  VIEW USUARIO_DATOS AS (select U.ID_USUARIO, V.TITULO,CA.NOMBRE  
from USUARIO U, video V, CANAL CA 
where V.CANAL_ID_CANAL=CA.ID_CANAL AND U.CANAL_ID_CANAL=CA.ID_CANAL AND U.ALIAS = USER
)with read only;

--Desde system concedemos los permisos para acceder a las vistas
GRANT SELECT ON U_ADMINISTRADOR.PAGO_TOTAL_VIDEO TO U_CONSULTOR;
GRANT SELECT ON U_ADMINISTRADOR.CANAL_DINERO_TOTAL TO U_CONSULTOR;
GRANT SELECT ON U_ADMINISTRADOR.VIDEOS_CON_DENUNCIA TO U_CONSULTOR; 
GRANT SELECT ON U_ADMINISTRADOR.VIDEO_ESTADISTICAS TO U_CONSULTOR; 
GRANT SELECT ON U_ADMINISTRADOR.PORCENTAJES_VIDEO TO U_CONSULTOR;
GRANT SELECT on U_ADMINISTRADOR.USUARIO_DATOS to U_USUARIO;
GRANT SELECT, DELETE  ON U_ADMINISTRADOR.DENUNCIA TO U_AGENTE;
GRANT DELETE ON U_ADMINISTRADOR.VIDEO TO U_AGENTE;
GRANT INSERT, DELETE ON U_ADMINISTRADOR.NOTIFICACION TO U_AGENTE; 